version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"
      assignees:
          - "mackilinen"

    - package-ecosystem: "npm"
      directory: "/visual-studio-code"
      schedule:
          interval: "daily"
      assignees:
          - "mackilinen"
