name: Dependency Update

on:
    pull_request:

jobs:
    build:
        name: Auto merge
        runs-on: ubuntu-latest
        if: github.actor == 'dependabot[bot]'
        steps:
            - name: "@dependabot merge"
              uses: actions/github-script@v2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const fromRegEx = /from v?(?<major>0|[1-9]\d*)/;
                      const toRegEx = /to v?(?<major>0|[1-9]\d*)/;
                      const title = context.payload.pull_request.title;
                      const fromMajor = title.match(fromRegEx).groups.major;
                      const toMajor = title.match(toRegEx).groups.major;
                      if (fromMajor === toMajor) {
                          await github.issues.createComment({
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            issue_number: context.issue.number,
                            body: '@dependabot merge'
                          })
                      }
